data:
  dataset_name: PathMNIST
  data_dir: ./data/pathmnist
  image_size: 128
  batch_size: 16
  num_workers: 4
  mask_folder: null
  augment_data: false
  val_split: 0.2
  test_split: 0.2

model:
  pretrained_model_id: runwayml/stable-diffusion-v1-5
  controlnet_id: null
  use_lora: false
  lora_rank: 4
  trainable_modules: []
  mixed_precision: fp16

training:
  output_dir: output/pathmnist_canny_demo
  downstream_learning_rate: 1e-4
  downstream_num_epochs: 20
  seed: 42
  log_wandb: false
  wandb_project: medical-controlnet-demo
  wandb_run_name: pathmnist-canny-demo

inference:
  controlnet_inference_id: lllyasviel/sd-controlnet-canny
  conditioning_type: canny
  num_inference_steps: 30
  guidance_scale: 7.0
  num_images_per_prompt: 1
  prompts:
    - "High-resolution histopathology slide showing colon tissue"
    - "Microscopic view of normal colorectal glands"
    - "Histology image of adipose tissue near colon section"
    - "Colorectal cancer cells, H&E stain"
    - "Pathology slide: adenocarcinoma in colon tissue"
    - "Lymphatic tissue in colorectal histology"
    - "Muscularis propria layer, colon histology"
    - "Well-differentiated colorectal carcinoma histology"