data:
  dataset_name: bci_dataset
  data_dir: data/bci_dataset
  image_size: 512
  batch_size: 4
  num_workers: 4
  mask_folder: masks
  augment_data: true
  val_split: 0.1
  test_split: 0.1

model:
  pretrained_model_id: runwayml/stable-diffusion-v1-5
  controlnet_id: null
  use_lora: false
  lora_rank: 4
  trainable_modules:
    - down_blocks
    - mid_block
    - up_blocks
  mixed_precision: fp16

training:
  output_dir: output
  learning_rate: 1.0e-05
  num_epochs: 100
  save_steps: 500
  eval_steps: 100
  gradient_accumulation_steps: 1
  seed: 42
  log_wandb: false
  wandb_project: medical-controlnet
  wandb_run_name: null

inference:
  num_inference_steps: 50
  guidance_scale: 7.5
  num_images_per_prompt: 1
  prompts:
    - A high-quality MRI scan of the brain showing a tumor
    - A clear histopathology image showing cancer cells
    - A chest X-ray showing pneumonia 