# Configuration for MRI Brain Tumor Generation Project

# Base paths
paths:
  data_dir: "./data"
  output_dir: "./outputs"
  models_dir: "./models"
  logs_dir: "./logs"

# Dataset settings
dataset:
  # BraTS dataset configuration
  brats:
    path: "./data/BraTSReg_Training_Data_v2"
    train_val_split: 0.8
    modalities: ["t1", "t1ce", "t2", "flair"]
    # Segmentation classes in BraTS
    # 0: background, 1: necrotic tumor core, 2: peritumoral edema, 4: enhancing tumor
    classes: [0, 1, 2, 4]
    resolution: [240, 240, 155]
    preprocess:
      normalize: true
      clip_percentiles: [0.5, 99.5]
      standardize: true

# Model configurations
models:
  # ControlNet configuration
  controlnet:
    base_model: "stabilityai/stable-diffusion-2-1-base"
    pretrained_model_path: null  # Set to path to use pretrained model
    resolution: 512
    train_batch_size: 4
    num_train_epochs: 100
    gradient_accumulation_steps: 1
    learning_rate: 1.0e-5
    lr_scheduler: "constant"
    lr_warmup_steps: 0
    mixed_precision: "fp16"
    seed: 42
    conditioning_scale: 1.0
    # Training options
    use_8bit_adam: true
    enable_xformers: true
    checkpointing_steps: 500
    validation_steps: 100
    tracker: "wandb"  # Options: "wandb", "tensorboard", null

  # LoRA adapter configuration
  lora:
    base_model: "stabilityai/stable-diffusion-2-1-base"
    resolution: 512
    train_batch_size: 4
    num_train_epochs: 100
    gradient_accumulation_steps: 1
    learning_rate: 1.0e-4
    lr_scheduler: "cosine"
    lr_warmup_steps: 500
    mixed_precision: "fp16"
    seed: 42
    # LoRA specific settings
    rank: 16
    alpha: 32
    # Training options
    use_8bit_adam: true
    enable_xformers: true
    checkpointing_steps: 500
    validation_steps: 100
    tracker: "wandb"  # Options: "wandb", "tensorboard", null

  # SAM2 configuration
  sam:
    model_type: "hf-hub:facebook/sam2"
    checkpoint: null  # Set to use local checkpoint
    device: "cuda"
    return_single_mask: false
    points_per_side: 32
    points_per_batch: 64
    pred_iou_thresh: 0.88
    stability_score_thresh: 0.95
    crop_n_layers: 0
    crop_n_points_downscale_factor: 1
    min_mask_region_area: 100

# Generation settings
generation:
  inference:
    num_inference_steps: 50
    guidance_scale: 7.5
    negative_prompt: "blurry, low quality, distorted, incorrect anatomy, unrealistic"
    seed: null  # Set to integer for reproducible generation
    height: 512
    width: 512
    batch_size: 1
    num_images_per_prompt: 1
    controlnet_conditioning_scale: 1.0
    output_type: "pil"  # Options: "pil", "numpy", "latent"
    use_lora: true  # Whether to use LoRA adapter
    lora_scale: 0.8  # Scale for LoRA influence

  # Tumor description settings
  tumor:
    types: ["glioblastoma", "meningioma", "metastatic", "low-grade glioma"]
    locations: ["frontal lobe", "temporal lobe", "parietal lobe", "occipital lobe", "cerebellum"]
    sizes: ["small", "medium", "large"]
    shapes: ["round", "irregular", "infiltrative"]
    effects: ["mass effect", "midline shift", "compression", "edema"]
    enhancement: ["ring-enhancing", "homogeneously enhancing", "non-enhancing"]
    # Probability of including each feature in prompt (0-1)
    feature_probabilities:
      location: 0.9
      size: 0.8
      shape: 0.7
      effects: 0.6
      enhancement: 0.7

# Logging and visualization
logging:
  level: "INFO"
  save_images: true
  save_metadata: true
  wandb:
    project: "mri-generation"
    entity: null  # Set to your wandb username
    log_images: true

visualization:
  show_grid: true
  grid_cols: 4
  colormap: "gray"
  mask_colors:
    necrotic_core: [255, 0, 0]  # Red
    edema: [0, 255, 0]          # Green
    enhancing: [0, 0, 255]      # Blue
  mask_alpha: 0.3 